// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Resources.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DeleteGroupResourceModel
    {
        /// <summary>
        /// Initializes a new instance of the DeleteGroupResourceModel class.
        /// </summary>
        public DeleteGroupResourceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeleteGroupResourceModel class.
        /// </summary>
        public DeleteGroupResourceModel(string name = default(string))
        {
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

    }
}
