// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Resources.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GroupResourceModel
    {
        /// <summary>
        /// Initializes a new instance of the GroupResourceModel class.
        /// </summary>
        public GroupResourceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroupResourceModel class.
        /// </summary>
        public GroupResourceModel(string name = default(string), GroupItem value = default(GroupItem))
        {
            Name = name;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public GroupItem Value { get; set; }

    }
}
