// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Resources.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ImageResourceModel
    {
        /// <summary>
        /// Initializes a new instance of the ImageResourceModel class.
        /// </summary>
        public ImageResourceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImageResourceModel class.
        /// </summary>
        public ImageResourceModel(string name = default(string), byte[] data = default(byte[]))
        {
            Name = name;
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public byte[] Data { get; set; }

    }
}
