// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Resources.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ImageResource
    {
        /// <summary>
        /// Initializes a new instance of the ImageResource class.
        /// </summary>
        public ImageResource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImageResource class.
        /// </summary>
        public ImageResource(string name = default(string), string url = default(string))
        {
            Name = name;
            Url = url;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

    }
}
