// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Resources.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextResource
    {
        /// <summary>
        /// Initializes a new instance of the TextResource class.
        /// </summary>
        public TextResource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextResource class.
        /// </summary>
        public TextResource(string lang = default(string), string name = default(string), string value = default(string))
        {
            Lang = lang;
            Name = name;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Lang")]
        public string Lang { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

    }
}
